[package]
edition = "2018"
name = "speedruns"
publish = false
version = "2.4.11"
[dependencies]
bincode = "1.1.3"
derive_more = "0.14.0"
env_logger = "0.6.1"
err-derive = "0.1.5"
flate2 = "1.0.7"
futures = "*"
getset = "0.0.7"
hyper = "0.12.28"
itertools = "0.8.0"
lazy-init = "*"
lazy_static = "1.3.0"
log = "0.4.6"
maud = "0.20.0"
no-panic = "*"
regex = "1.1.6"
reqwest = "0.9.15"
serde_json = "1.0.39"
tempfile = "3.0.7"
url_serde = "0.2.0"
validator = "0.8.0"
validator_derive = "0.8.0"
webbrowser = "0.5.1"
xz2 = "0.1.6"

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"

[dependencies.rusqlite]
features = ["functions", "chrono", "serde_json", "bundled"]
version = "0.18.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.90"

[dependencies.url]
features = ["serde"]
version = "1.7.2"

[lib]
name = "speedruns"
path = "src/lib.rs"
