[package]
name = "speedruncom-data-tools"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
name = "speedruncom_data_tools"
path = "src/lib.rs"

[[bin]]
name = "scrape"
path = "src/bin/scrape.rs"

[[bin]]
name = "verify"
path = "src/bin/verify.rs"

[[bin]]
name = "normalize"
path = "src/bin/normalize.rs"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
reqwest = "0.9.15"
flate2 = "1.0.7"
log = "0.4.6"
env_logger = "0.6.1"
rusqlite = { version = "0.18.0", features = [
    "functions",
    "chrono",
    "serde_json",
    "bundled",
] }
tempfile = "3.0.7"
getset = "0.0.7"
xz2 = "0.1.6"
chrono = { version = "0.4.6", features = ["serde"] }
bincode = "1.1.3"
derive_more = "0.14.0"
validator = "0.8.0"
validator_derive = "0.8.0"
url = { version = "1.7.2", features = ["serde"] }
url_serde = "0.2.0"
