[package]
edition = "2018"
license = "MIT"
name = "speedruns"
version = "0.0.5"

default-run = "serve"

[dependencies]
derive_more = "0.99.2"
env_logger = "0.7.1"
err-derive = "0.1.5"
flate2 = "1.0.13"
getset = "0.0.9"
itertools = "0.8.2"
lazy_static = "1.4.0"
log = "0.4.8"
no-panic = "0.1.12"
percent-encoding = "2.1.0"
regex = "1.3.1"
remain = "0.2.0"
reqwest = "0.9.24"
serde_json = "1.0.44"
tempfile = "3.1.0"
unidecode = "0.3.0"
url_serde = "0.2.0"
validator = "0.10.0"
validator_derive = "0.10.0"
async-std = "1.4.0"
juniper = "0.14.2"
juniper_hyper = "0.5.2"
pretty_env_logger = "0.3.1"
actix-web = "2.0.0"
actix = "0.9.0"
actix-rt = "1.0.0"
actix-cors = "0.2.0"

[dependencies.futures]
version = "0.3.1"
features = ["compat"]

[dependencies.chrono]
features = ["serde"]
version = "0.4.10"

[dependencies.serde]
features = ["derive"]
version = "1.0.104"

[dependencies.url]
features = ["serde"]
version = "2.1.0"
