[package]
name = "flamerun"
version = "0.0.0"
authors = ["Jeremy Banks <_@jeremy.ca>"]
edition = "2018"
publish = false

[dependencies]
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
reqwest = "0.9.0"
chrono = { version = "0.4.0", features = ["serde"] }
log = "0.4.0"
fs2 = "0.4.0"
env_logger = "0.5.0"
itertools = "0.7.8"
