comment_width = 92
format_code_in_doc_comments = true
inline_attribute_width = 64
match_arm_blocks = false
max_width = 92
merge_imports = true
newline_style = "Unix"
reorder_impl_items = true
struct_field_align_threshold = 64
trailing_semicolon = false
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true