{
  "version": "2.1",
  "workflows": {
    "version": 2,
    "workflow": {
      "jobs": [
        "build",
        { "test": { "requires": ["build"] } },
        { "formatting": { "requires": ["build"] } },
        { "warnings": { "requires": ["build"] } },
        { "updates": { "requires": ["build"] } },
      ]
    }
  },
  "jobs": {
    "build": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
            "v1-cargo-cache-"
          ]
        }},
        {"run": "rustup component add rustfmt"},
        {"run": "cargo build --lib"},
        {"save_cache": {
          "paths": [
            "/usr/local/cargo/registry",
            "target/"
          ],
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }}
      ]
    },

    "test": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
            "v1-cargo-cache-"
          ]
        }},
        {"run": "cargo test --lib"},
      ]
    },

    "formatting": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
            "v1-cargo-cache-"
          ]
        }},
        {"run": "cargo fmt --all -- --check"},
      ]
    },

    "warnings": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
            "v1-cargo-cache-"
          ]
        }},
        {"run": "RUSTFLAGS=\"-D warnings\" cargo build --lib"},
      ]
    },

    "updates": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
            "v1-cargo-cache-"
          ]
        }},
        {"run": "cargo update --locked"},
      ]
    }
  }
}
