{
  "version": "2.1",
  "jobs": {
    "build": {
      "all": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }},
        {"run": "cargo build --lib"},
        {"run": "cargo test --lib"},
        {"run": "cargo doc --lib"},
        {"save_cache": {
          "paths": [
            "/usr/local/cargo/registry",
            "target/"
          ],
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }}
      ]
    }
  }
}
