{
  "version": "2.1",
  "workflows": {
    "version": 2,
    "workflow": {
      "jobs": [
        "build --lib",
        { "test --lib": { "requires": ["build --lib"] } },
        { "build --lib --deny warnings": { "requires": ["build --lib"] } },
        { "cargo fmt": { "requires": ["build --lib"] } },
        { "cargo update": { "requires": ["build --lib"] } },
      ]
    }
  },
  "jobs": {
    "build --lib": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
            "v1-cargo-cache-"
          ]
        }},
        {"run": "cargo build --lib"},
        {"save_cache": {
          "paths": [
            "/usr/local/cargo/registry",
            "target/"
          ],
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }}
      ]
    },

    "test --lib": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "cargo test --lib"},
      ]
    },

    "cargo fmt": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "rustup component add rustfmt"},
        {"run": "cargo fmt --all -- --check"},
      ]
    },

    "build --lib --deny warnings": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "RUSTFLAGS=\"--deny warnings\" cargo build --lib"},
      ]
    },

    "cargo update": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "cargo update --locked"},
      ]
    }
  }
}
