{
  "version": "2.1",
  "executors": {
    "executor": {"docker": [
      {"image": "circleci/rust:latest"}
    ] }
  },
  "workflows": {
    "version": 2,
    "speedruns": {
      "jobs": [
        "build",
        { "test": { "requires": ["build"] } },
        { "code formatted": { "requires": ["build"] } },
        { "dependencies updated": { "requires": ["build"] } },
        { "warnings resolved": { "requires": ["test"] } },
        { "could publish": { "requires": [
          "build",
          "test",
          "warnings resolved",
          "code formatted",
          "dependencies updated",
        ] } },
      ]
    }
  },
  "jobs": {
    "build": {
      "executor": "executor",
      "steps": [
        "checkout",
        {"restore_cache": {
          "keys": [
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}",
            "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}",
          ]
        }},
        {"run": "cargo build --all"},
        {"save_cache": {
          "paths": [
            "/usr/local/cargo/registry",
            "target/"
          ],
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }}
      ]
    },

    "test": {
      "executor": "executor",
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "cargo test --all"},
      ]
    },

    "code formatted": {
      "executor": "executor",
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "rustup component add rustfmt"},
        {"run": "cargo fmt --all -- --check"},
      ]
    },

    "warnings resolved": {
      "executor": "executor",
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "RUSTFLAGS=\"--deny warnings\" cargo build --all"},
      ]
    },

    "dependencies updated": {
      "executor": "executor",
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "cargo update --locked"},
      ]
    },

    "could publish": {
      "executor": "executor",
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}-{{ .Revision }}"
        }},
        {"run": "cargo publish --dry-run"},
      ]
    }
  }
}
