{
  "version": "2.1",
  "workflows": {
    "version": 2,
    "workflow": {
      "jobs": [
        "build",
        { "test": { "requires": ["build"] } },
        { "lint": { "requires": ["build"] } },
        { "warnings": { "requires": ["build"] } },
      ]
    }
  },
  "jobs": {
    "build": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }},
        {"run": "cargo build --lib"},
        {"save_cache": {
          "paths": [
            "/usr/local/cargo/registry",
            "target/"
          ],
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }}
      ]
    },

    "test": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }},
        {"run": "cargo test --lib"},
      ]
    },

    "lint": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }},
        {"run": "cargo fmt"},
      ]
    },

    "warnings": {
      "docker": [
        {"image": "circleci/rust:latest"}
      ],
      "steps": [
        "checkout",
        {"restore_cache": {
          "key": "v1-cargo-cache-{{ checksum \"Cargo.lock\" }}"
        }},
        {"run": "RUSTFLAGS=\"-D warnings\" cargo build --lib"},
      ]
    }
  }
}
