name: Actions
on: [push]

jobs:
  my-job:
    name: Action

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: checkout source
        uses: actions/checkout@v1

      - name: caching - rustup toolchain - preparation
        id: rustup-cache
        run: echo "::set-output name=toolchain::$(cat rust-toolchain)"

      - name: caching - rustup toolchain
        uses: actions/cache@v1
        with:
          path: ~/.rustup/toolchains/
          key:
            ${{ runner.os }}-rustup-${{ steps.rustup-cache.outputs.toolchain }}
          restore-key: ${{ runner.os }}-rustup-

      - name: caching - cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-key: ${{ runner.os }}-cargo-registry-

      - name: caching - cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-key: ${{ runner.os }}-cargo-index-

      - name: caching - cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock')}}
          restore-keys: ${{ runner.os }}-cargo-build-

      - name: preparation - install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ steps.rustup-cache.outputs.toolchain }}

      - name: preparation - install node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: preparation - install yarn
        run: npm install -g yarn

      - name: caching - yarn - preparation
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: caching - yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: run - yarn install
        run: yarn install

      - name: run - cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: run - cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: run - cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: run - cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -W warnings
